#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=8:dc,vmem=32gb,walltime=48:00:00 
#PBS -M zhenyisong@gmail.com 
#PBS -m abe
#PBS -N miRNA
#PBS -j oe
#PBS -e /home/zhenyisong/data/cardiodata/SRP056382
#PBS -o /home/zhenyisong/data/cardiodata/SRP056382

## qsub /home/zhenyisong/data/wanglilab/wangcode/miRNA-Bowtie.script
## http://seqanswers.com/forums/showthread.php?t=3775
## http://stackoverflow.com/questions/947897/block-comments-in-a-shell-script

## -a/--all
## Report all valid alignments per read or pair (default: off)
## -k <int>
## Report up to <int> valid alignments per read or pair (default: 1)
## -m <int>
## Suppress all alignments for a particular read or pair if more than <int> reportable alignments exist for it.
## -n/--seedmms <int>
## Maximum number of mismatches permitted in the "seed",
## -v <int>
## Report alignments with at most <int> mismatches
## -l/--seedlen <int>
## The "seed length"; i.e., the number of bases on the high-quality end of the read to
## --best
## Make Bowtie guarantee that reported singleton alignments are "best" in terms of stratum
## --strata
## If many valid alignments exist and are reportable 
## -e/--maqerr <int>
## Maximum permitted total of quality values at all mismatched read positions throughout the entire 

#bowtie -a -n 0 -l 15 -e 99999 -k 200  --best --strata --chunkmbs 128
#bowtie genome -p 10 -a --best --strata -l 10 -m 1 --chunkmbs 128 -q --sam SRR1973857.fastq >SRR1973857.sam
#bowtie human --best --strata -k 200 -a -n 0 -l 15 -e 9999 --chunkmbs 500 -q --sam SRR039611.fastq >SRR039611.sam
##bowtie genome -p 10 -v 0 -a --best --strata -norc -q --sam SRR039611.fastq >SRR039611.sam
#bowtie mature_hsa -p 8 -v 0 -a --best --strata -norc -q --sam SRR039611.fastq >SRR039611.sam
#bowtie mature_hsa -p 8 -n 1 -l 8 -a --best --strata -q --sam SRR039611.fastq >SRR039611.sam
#samtools view -bS SRR1973857.sam | samtools sort -n -@ 8 - SRR1973857


## you need to define the genome seqeunce 
##   human  /home/zhenyisong/data/bringback/igenome/Homo_sapiens/NCBI/GRCh38/Sequence/BowtieIndex/genome.fa
##   mouse
## bowtie1 index
##   human  /home/zhenyisong/data/bringback/igenome/Homo_sapiens/NCBI/GRCh38/Sequence/BowtieIndex
##   mouse

##---
## miRBase dataset
##
## /home/zhenyisong/data/genome/miRNA
##---

##
## used commond
##  $bowtie genome -p 10 -a --best --strata -l 10 -m 1 --chunkmbs 128 -q --sam $base.fastq > $base.sam
source /etc/profile
cd /home/zhenyisong/data/cardiodata/SRP056382
fastq='/home/zhenyisong/data/cardiodata/SRP056382'
hsa='/home/zhenyisong/data/genome/miRNA/hsa.gff3'
miRNAadaptor='TGGAATTCTCGGGTGCCAAGG'
files=(*.fastq)
len=${#files[@]}


bwa='/usr/local/bin/bwa'
cutadapt='/opt/rocks/bin/cutadapt'
#ln -s /home/zhenyisong/data/bringback/igenome/Homo_sapiens/NCBI/GRCh38/Sequence/BowtieIndex/genome.fa ./

bwa_genome='/home/zhenyisong/data/bringback/igenome/Homo_sapiens/NCBI/GRCh38/Sequence/BWAIndex/genome.fa'
cd /home/zhenyisong/data/cardiodata/SRP056382
##rm -rf bwa
##mkdir bwa
##cd bwa
####ln -s $bwa_genome ./
####$bwa index -a bwtsw genome.fa
##for (( i=0; i<${len}; i++ ));
##do
##    filename=${files[$i]}
##    base=${filename%.fastq}
##    #$cutadapt -e 0.15 -O 7 -m 15 -a $miRNAadaptor $fastq/$base.fastq -o $base.cutadapt.fastq
##    $bwa aln -t 8 -n 1 -o 0 -e 0 -l 8 -k 0 genome.fa $base.cutadapt.fastq > $base.sai
##    $bwa samse genome.fa $base.sai $fastq/$base.fastq | samtools sort -n -@ 8 - $base
##    python -m HTSeq.scripts.count -s no --stranded=no -r name -f bam -t miRNA -m union -i Name -q $base.bam $hsa > $base.txt
##    #$bwa samse genome.fa SRR1922516.sai SRR1922516.fastq | samtools sort -n -@ 8 - SRR1922516
##    #python -m HTSeq.scripts.count -s no --stranded=no -r name -f bam -t miRNA_primary_transcript -m union -i Name $base.bam $hsa > $base.txt
##    #python -m HTSeq.scripts.count -s no --stranded=no -r name -f bam -t miRNA -m union -i Name SRR1922516.bam $hsa > SRR1922516.txt
##done
##

bowtie='/usr/local/bin/bowtie'
cd /home/zhenyisong/data/cardiodata/SRP056382/bowtie/adaptor
ln -s /home/zhenyisong/data/bringback/igenome/Homo_sapiens/NCBI/GRCh38/Sequence/BowtieIndex/* ./

for (( i=0; i<${len}; i++ ));
do
    filename=${files[$i]}
    base=${filename%.fastq}
    $cutadapt -e 0.15 -O 7 -m 15 -a $miRNAadaptor $fastq/$base.fastq -o $base.cutadapt.fastq
    $bowtie genome -p 4 -n 1 -l 8 -a --best --strata --sam $base.cutadapt.fastq > $base.sam
    samtools view -bS $base.sam | samtools sort -n -@ 8 - $base
    python -m HTSeq.scripts.count -s no --stranded=no -r name -f bam -t miRNA -m union -i Name -q $base.bam $hsa > $base.txt
done
##
##
## $bwa aln -t 10 -n 1 -o 0 -e 0 -k 1 genome.fa SRR1922516.cutadapt.fastq > SRR1922516.sai
## $bwa samse genome.fa SRR1922516.sai SRR1922516.cutadapt.fastq | samtools sort -n -@ 8 - SRR1922516
## python -m HTSeq.scripts.count -s no --stranded=no -r name -f bam -t miRNA -m union -i Name -q SRR1922516.bam $hsa > SRR1922516.bwa.txt
##

##$bowtie genome -p 10 -n 1 -l 10 -a --best --strata --sam SRR1922516.cutadapt.fastq > SRR1922516.trimed.sam
##samtools view -bS SRR1922516.trimed.sam| samtools sort -n -@ 8 - SRR1922516.trimed
##python -m HTSeq.scripts.count -s no --stranded=no -r name -f bam -t miRNA -m union -i Name SRR1922516.trimed.bam $hsa > SRR1922516.trimed.txt
##1. BWA 0.7.4: bwa aln -n 1 -o 0 -e 0 -k 1 -t 4
##2. BWA 0.7.4 (0 mismatch in seed): bwa aln -n 1 -o 0 -e 0 -l 8 -k 0 -t 4
##3. Bowtie 0.12.9: bowtie -