#!/bin/bash
# see graph generated by R code
# generate the Ino80.human.cDNA.fa
# imported from email record
# use the webiste
# http://www.ebi.ac.uk/Tools/sfc/
# and use the linux command 
# cat > Human.Ino80.fa

cd /home/zhenyisong/biodata/wanglab/zongna/Ino80Data   
## discarded the hisat2, need confirmation!
##hisat2-build human.Ino80.fa HumanIno80cDNA
##
##cd /home/zhenyisong/biodata/wanglab/zongna/Ino80Data/rawdata
##hisat2 -x ../HumanIno80cDNA -q -p 15 -U CM_GFP_1_S11_R1_001.fastq --tmo -S CM_GFP_1.sam
##hisat2 -x ../HumanIno80cDNA -q -p 15 -U CM_GFP_2_S13_R1_001.fastq --tmo -S CM_GFP_2.sam
##hisat2 -x ../HumanIno80cDNA -q -p 15 -U CM_ino80OE_1_S12_R1_001.fastq --tmo -S CM_Ino80_1.sam
##hisat2 -x ../HumanIno80cDNA -q -p 15 -U CM_ino80OE_2_S14_R1_001.fastq --tmo -S CM_Ino80_2.sam
##
### https://www.biostars.org/p/145053/
##samtools view -Sb -@ 15 CM_Ino80_2.sam -o CM_Ino80_2.bam
##samtools index  CM_Ino80_2.bam
##samtools idxstats CM_Ino80_2.bam
##
### positive control
##hisat2-build ../kallisto/RatIno80cDNA.fa RatIno80cDNA
##
##cd /home/zhenyisong/biodata/wanglab/zongna/Ino80Data/rawdata
##hisat2 -x RatIno80cDNA -q -p 15 -U ../rawdata/CM_GFP_1_S11_R1_001.fastq --tmo -S CM_GFP_1.sam
##hisat2 -x RatIno80cDNA -q -p 15 -U ../rawdata/CM_GFP_2_S13_R1_001.fastq --tmo -S CM_GFP_2.sam
##hisat2 -x RatIno80cDNA -q -p 15 -U ../rawdata/CM_ino80OE_1_S12_R1_001.fastq --tmo -S CM_Ino80_1.sam
##hisat2 -x RatIno80cDNA -q -p 15 -U ../rawdata/CM_ino80OE_2_S14_R1_001.fastq --tmo -S CM_Ino80_2.sam

# https://www.biostars.org/p/145053/
samtools view -Sb -@ 15 CM_Ino80_2.sam -o CM_Ino80_2.bam
samtools index  CM_Ino80_2.bam
samtools idxstats CM_Ino80_2.bam
#---
# |samtools view -F 260 -@ 15 -|cut -f 3 | sort | uniq -c | awk '{printf("%s\t%s\n", $2, $1)}' > CM_Ino80_2.txt



# https://pachterlab.github.io/kallisto/manual
# Important note: only supply one sample at a time to kallisto. 
# The multiple FASTQ (pair) option is for users who have samples 
# that span multiple FASTQ files.
kallisto index -i HumanIno80cDNA -k 25 ../human.Ino80.fa

kallisto quant -i HumanIno80cDNA -o quantification --single --plaintext -l 200 -s 10 -t 15 ../rawdata/CM_GFP_1_S11_R1_001.fastq ../rawdata/CM_GFP_2_S13_R1_001.fastq ../rawdata/CM_ino80OE_1_S12_R1_001.fastq ../rawdata/CM_ino80OE_2_S14_R1_001.fastq
kallisto quant -i HumanIno80cDNA -o quantification --single --plaintext -l 200 -s 20 -t 15 ../rawdata/CM_ino80OE_2_S14_R1_001.fastq
#target_id       length  eff_length      est_counts      tpm
#EMBOSS_Human_Ino80      6036    5837    597     1e+06
kallisto quant -i HumanIno80cDNA -o quantification --single --plaintext -l 200 -s 20 -t 15 ../rawdata/CM_GFP_1_S11_R1_001.fastq
#target_id       length  eff_length      est_counts      tpm
#EMBOSS_Human_Ino80      6036    5837    442     1e+06

# positive control
kallisto index -i RatIno80cDNA -k 25 RatIno80cDNA.fa
kallisto quant -i RatIno80cDNA -o quantification --single --plaintext -l 200 -s 20 -t 15 ../rawdata/CM_GFP_1_S11_R1_001.fastq
#target_id       length  eff_length      est_counts      tpm
#NCBI_RAT_INO80  6017    5818    1223    1e+06
kallisto quant -i RatIno80cDNA -o quantification --single --plaintext -l 200 -s 20 -t 15 ../rawdata/CM_ino80OE_2_S14_R1_001.fastq
#target_id       length  eff_length      est_counts      tpm
#NCBI_RAT_INO80  6017    5818    1502    1e+06


# salmon
# http://combine-lab.github.io/salmon/
salmon index -t ../human.Ino80.fa -i humanIno80
salmon quant -i humanIno80 -l U -p 15 -r ../rawdata/CM_ino80OE_2_S14_R1_001.fastq -o quantification
#Name    Length  EffectiveLength TPM     NumReads
#EMBOSS_Human_Ino80      6036    5762    1e+06   269
salmon quant -i humanIno80 -l U -p 15 -r ../rawdata/CM_GFP_1_S11_R1_001.fastq -o quantification
#Name    Length  EffectiveLength TPM     NumReads
#EMBOSS_Human_Ino80      6036    5762    1e+06   193

# positive control
salmon index -t ../kallisto/RatIno80cDNA.fa -i ratIno80
salmon quant -i ratIno80 -l U -p 15 -r ../rawdata/CM_ino80OE_2_S14_R1_001.fastq -o quantification
#Name    Length  EffectiveLength TPM     NumReads
#NCBI_RAT_INO80  6017    5768    1e+06   1451
salmon quant -i ratIno80 -l U -p 15 -r ../rawdata/CM_GFP_1_S11_R1_001.fastq -o quantification
#Name    Length  EffectiveLength TPM     NumReads
#NCBI_RAT_INO80  6017    5768    1e+06   1224


